name: Keep Supabase Active

on:
  schedule:
    - cron: "0 0 * * 1,3,5,0" # Midnight UTC on Mon, Wed, Fri, Sun
  workflow_dispatch: # Allow manual triggering

jobs:
  ping-supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Send keep-alive request
        run: |
          curl --fail --retry 10 -X GET "${{ secrets.KEEP_ALIVE_URL }}?ownerId=${{ secrets.OWNER_ID }}"
